---
apiVersion: v1
kind: Template
metadata:
  name: rules-processing
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: rules-processing
  spec:
    envName: ${ENV_NAME}
    testing:
      iqePlugin: ccx
    objectStore:
      - ${SOURCE_S3_BUCKET}
    deployments:
      - name: instance
        replicas: ${{REPLICAS}}
        webServices:
          public:
            enabled: false
          private:
            enabled: false
          metrics:
            enabled: true
        podSpec:
          image: ${IMAGE}:${IMAGE_TAG}
          command: ["ccx-messaging"]
          args: ["/data/config.yaml"]
          env:
            - name: CLOWDER_ENABLED
              value: ${CLOWDER_ENABLED}
            - name: LOGGING_TO_CW_ENABLED
              value: ${LOGGING_TO_CW_ENABLED}
            - name: CW_STREAM_NAME
              value: ${CW_LOG_STREAM}
            - name: AWS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudwatch
                  key: aws_region
                  optional: true
            - name: CW_LOG_GROUP
              valueFrom:
                secretKeyRef:
                  name: cloudwatch
                  key: log_group_name
                  optional: true
            - name: CW_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cloudwatch
                  key: aws_access_key_id
                  optional: true
            - name: CW_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudwatch
                  key: aws_secret_access_key
                  optional: true
            # Sentry configuration
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: dsn
                  name: rules-processing-dsn
                  optional: true
            - name: SENTRY_ENVIRONMENT
              value: ${ENV_NAME}
            - name: SENTRY_ENABLED
              value: ${SENTRY_ENABLED}

          volumeMounts:
            - mountPath: /data
              name: rules-processing-config
          volumes:
            - configMap:
                name: rules-processing-config-map
              name: rules-processing-config
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}

          readinessProbe:
            httpGet:
              path: /metrics
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 1
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /metrics
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 1
            # Wait for 10x10 seconds
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 10

    kafkaTopics:
    - name: synced-topic
      topicName: ${KAFKA_SYNCED_TOPIC}
      replicas: 3
      partitions: 1
    - name: rules-topic
      topicName: ${KAFKA_RULES_TOPIC}
      replicas: 3
      partitions: 1
    - name: payload-tracker-topic
      topicName: ${PAYLOAD_TRACKER_TOPIC}
      partitions: 1

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: rules-processing-config-map
    labels:
      app: rules-processing
  data:
    config.yaml: |-
      plugins:
        packages:
          - ccx_rules_ocp
          - ccx_rules_processing
      service:
        extract_timeout:
        extract_tmp_dir:
        format: insights.formats._json.JsonFormat
        target_components: []
        unpacked_archive_size_limit: 1000000000

        consumer:
          name: ccx_messaging.consumers.synced_archive_consumer.SyncedArchiveConsumer
          kwargs:
            incoming_topic: ${KAFKA_SYNCED_TOPIC}
            group.id: ${KAFKA_GROUP_ID}
            bootstrap.servers: ${KAFKA_URL}

        downloader:
          name: ccx_messaging.downloaders.s3_downloader.S3Downloader
          kwargs:
            bucket: ${SOURCE_S3_BUCKET}

        publisher:
          name: ccx_messaging.publishers.idp_rule_processing_publisher.IDPRuleProcessingPublisher
          kwargs:
            outgoing_topic: ${KAFKA_RULES_TOPIC}
            bootstrap.servers: ${KAFKA_URL}

        watchers:
          - name: ccx_messaging.watchers.stats_watcher.StatsWatcher
            kwargs:
              prometheus_port: 8001
          - name: ccx_messaging.watchers.payload_tracker_watcher.PayloadTrackerWatcher
            kwargs:
              bootstrap.servers: ${KAFKA_URL}
              topic: ${PAYLOAD_TRACKER_TOPIC}
              service_name: rules-processing

        logging:
          version: 1
          disable_existing_loggers: false
          handlers:
            default:
              level: ${LOGLEVEL_STDOUT}
              class: logging.StreamHandler
              stream: ext://sys.stdout
              formatter: default

          formatters:
            default:
              format: '%(asctime)s %(name)s %(levelname)-8s %(message)s'
              datefmt: '%Y-%m-%d %H:%M:%S'

          root:
            level: ${LOGLEVEL_ROOT}
            handlers:
              - default

          loggers:
            ccx_messaging:
              level: ${LOGLEVEL_CCX_MESSAGING}

            insights_messaging:
              level: ${LOGLEVEL_INSIGHTS_MESSAGING}

            insights:
              level: ${LOGLEVEL_INSIGHTS}

            kafka:
              level: ${LOGLEVEL_KAFKA}
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "8000"
      prometheus.io/scheme: http
      prometheus.io/scrape: "true"
    name: rules-processing-prometheus-exporter
    labels:
      app: rules-processing
  spec:
    ports:
      - name: rules-processing-port-metrics
        port: 8001
        protocol: TCP
        targetPort: 8001
    selector:
      app: rules-processing

parameters:
  - description: Image name
    name: IMAGE
    value: quay.io/redhat-services-prod/obsint-processing-tenant/data-pipeline/data-pipeline
  - description: Image tag
    name: IMAGE_TAG
    required: true

  - description: Determines Clowder deployment
    name: CLOWDER_ENABLED
    value: "true"
  - description: ClowdEnv Name
    name: ENV_NAME
    required: true
  - name: CLOUDWATCH_DEBUG
    value: "false"
    required: true
  - name: CW_LOG_STREAM
    value: "rules-processing"

  - name: SENTRY_ENABLED
    value: "false"

  - description: Number of pods
    name: REPLICAS
    value: '1'

  - name: KAFKA_SYNCED_TOPIC
    description: "Incoming archive synced topic"
    value: "ccx.archive.synced"
  - name: KAFKA_GROUP_ID
    description: "Kafka group id"
    value: "ccx-rules-processing-service"
  - name : KAFKA_RULES_TOPIC
    description: "Outgoing rules topic"
    value: "ccx.insights.rules.results"
  - name: KAFKA_URL
    value: "mq-kafka:29092"

  - name: PAYLOAD_TRACKER_TOPIC
    value: platform.payload-status


  - name: SOURCE_S3_BUCKET
    description: "Source S3 bucket for object store configuration"
    value: "ccx-bucket"

  - name: CPU_LIMIT
    value: "1000m"
  - name: MEMORY_LIMIT
    value: "1000Mi"
  - name: CPU_REQUEST
    value: "700m"
  - name: MEMORY_REQUEST
    value: "600Mi"

  - name: LOGLEVEL_CCX_MESSAGING
    value: "INFO"
  - name: LOGLEVEL_INSIGHTS_MESSAGING
    value: "WARNING"
  - name: LOGLEVEL_INSIGHTS
    value: "WARNING"
  - name: LOGLEVEL_KAFKA
    value: "INFO"
  - name: LOGLEVEL_STDOUT
    value: "INFO"
  - name: LOGLEVEL_ROOT
    value: "WARNING"
  - name: LOGGING_TO_CW_ENABLED
    value: "true"
